### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by MikeSofaer** [d3y4n/instagraph#1]
I'm looking at using this for a little project, and there's no license file or any indication of whether I'm allowed to use it in production. I'm happy to make a pull request with an MIT license if you do want to license it that way. Otherwise adding "All Rights Reserved" or something to the README would make things clear.

Thanks!
-Michael

**Comment by d3y4n** [comment]
Hey Mike, feel free to use it, if you want, you can credit the PHP class by linking to http://webarto.com (optional), not your final product.

**Comment by d3y4n** [comment]
> Instagraph is open-sourced software licensed under the MIT License.
