### ISSUE TITLE
Version Problem

### ISSUE THREAD

**Issue by danielaugustoca** [d3y4n/instagraph#2]
I've uploaded your script at my host and some effects didn't work (Lomo, toaster and nashville). I saw that a user posted the same problem in: http://net.tutsplus.com/tutorials/php/create-instagram-filters-with-php/

Did you solve it? Would it be a version problem? How clould I solve it?

Thanks

**Comment by d3y4n** [comment]
Hi, problem is probably in your Imagemagick version, there is nothing you can do about it, except update, which is least painful.

**Comment by d3y4n** [comment]
I'm not sure yet what minimum version is required, there is no way for me to test it. Works on latest ones.
