### ISSUE TITLE
instagraph.me not working

### ISSUE THREAD

**Issue by tiltos** [d3y4n/instagraph#3]
Hi there, I like your code, and have used it successfully for me needs. I just wanted to give you the heads up the instagraph.me has been out of action for the last month, it can't seem to find the file it hashes to. 

On that note, I was wondering if you could perhaps give insight into the process that instagraph.me takes after a user has uploaded a file? Are you simply naming this file with a uid and using your .htaccess to reroute a page query to to a unique url?

**Comment by d3y4n** [comment]
Thank you for heads up, it appears I've set disk quota limit of 10GB, I removed limit and it is working as it was before.
http://instagraph.me/p/0baa90372a82f97d4623568071e09e67
(I will add another comment regarding your question)

**Comment by tiltos** [comment]
Haha, if anything, thats simply a measure of how popular your tutorial has been!
